### ISSUE TITLE
Erro ao atualizar usuario

### ISSUE THREAD

**Issue by yuri-spm** [yuri-spm/blog#4]
Ao tentar atualizar usuário ocorre o seguinte erro:

Fatal error: Uncaught TypeError: PDOStatement::execute(): Argument #1 ($params) must be of type ?array, string given in C:\laragon\www\blog\system\Core\Model.php:98 Stack trace: #0 C:\laragon\www\blog\system\Core\Model.php(98): PDOStatement->execute('e=teste14@teste...') #1 C:\laragon\www\blog\system\Model\UserModel.php(56): system\Core\Model->result() #2 C:\laragon\www\blog\system\Controller\Admin\AdminUser.php(89): system\Model\UserModel->save() #3 [internal function]: system\Controller\Admin\AdminUser->edit(25) #4 C:\laragon\www\blog\vendor\pecee\simple-router\src\Pecee\SimpleRouter\ClassLoader\ClassLoader.php(34): call_user_func_array(Array, Array) #5 C:\laragon\www\blog\vendor\pecee\simple-router\src\Pecee\SimpleRouter\Route\Route.php(117): Pecee\SimpleRouter\ClassLoader\ClassLoader->loadClassMethod(Object(system\Controller\Admin\AdminUser), 'edit', Array) #6 C:\laragon\www\blog\vendor\pecee\simple-router\src\Pecee\SimpleRouter\Router.php(427): Pecee\SimpleRouter\Route\Route->renderRoute(Object(Pecee\Http\Request), Object(Pecee\SimpleRouter\Router)) #7 C:\laragon\www\blog\vendor\pecee\simple-router\src\Pecee\SimpleRouter\Router.php(353): Pecee\SimpleRouter\Router->routeRequest() #8 C:\laragon\www\blog\vendor\pecee\simple-router\src\Pecee\SimpleRouter\SimpleRouter.php(69): Pecee\SimpleRouter\Router->start() #9 C:\laragon\www\blog\routers.php(49): Pecee\SimpleRouter\SimpleRouter::start() #10 C:\laragon\www\blog\index.php(11): require('C:\\laragon\\www\\...') #11 {main} thrown in C:\laragon\www\blog\system\Core\Model.php on line 98

**Comment by yuri-spm** [comment]
![image](https://github.com/yuri-spm/blog/assets/63649751/c42f3598-8afd-4821-99a5-1559c9611e94)
